feat(angular): Updates for Angular 7
As already sketched in https://github.com/ui-router/angular/issues/423,
we are already using Angular 7 with uirouter/angular over at opf/openproject
and meanwhile in production as well, so we can safely attest that the current
version of uirouter works unchanged with even the recent Angular 7.2.2 release
with only some minor hassle during the upgrade due to the peer depedndency.

This PR tries to add the dependency and a downstream test.

I had to bump the local typescript version to ensure RxJS is being
built, without it `ngc` will output the following errors

node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected.

This is due to this issue: https://github.com/ReactiveX/rxjs/issues/4511
Using the newest typescript also uncovered an issue in `uiSrefStatus.ts`.

In all downstream tests with TS < 2.8., I pinned rxjs to avoid the same
issue.